from tkinter import*
root=Tk()
root.title('Student form')
root.geometry('800x400')
namev=StringVar()
Snov=IntVar()
m1v=IntVar()
m2v=IntVar()
m3v=IntVar()
Snov.set('')
m1v.set('')
m2v.set('')
m3v.set('')
Label(root,text='Sno').grid(row=0,column=0)
Entry(root,textvariable=Snov).grid(row=0,column=1)
Label(root,text='Name').grid(row=1,column=0)
Entry(root,textvariable=namev).grid(row=1,column=1)
Label(root,text='m1').grid(row=2,column=0)
Entry(root,textvariable=m1v).grid(row=2,column=1)
Label(root,text='m2').grid(row=3,column=0)
Entry(root,textvariable=m2v).grid(row=3,column=1)
Label(root,text='m3').grid(row=4,column=0)
Entry(root,textvariable=m3v).grid(row=4,column=1)
root.mainloop()
