import datetime
from tkinter import *
root=Tk()
root.geometry('1600x700')
root.title("Restarant management System")

TopF=Frame(root,bg='#00FFFF',width=1600,height=150)
TopF.pack(side=TOP)
BottomF=Frame(root,bg="red",width=1600,height=50)
BottomF.pack(side=BOTTOM)
f1=Frame(root,width=900,height=600)
f1.pack(side=LEFT)
order1=IntVar()
fmeal=IntVar()
cmeal=IntVar()
mutton=IntVar()
crab=IntVar()
Label(f1,text="orderno").grid(row=0,column=0)
Entry(f1,textvariable=order1).grid(row=0,column=1)
order1.set("")
Label(f1,text="Fishmeal").grid(row=1,column=0)
Entry(f1,textvariable=fmeal).grid(row=1,column=1)
fmeal.set("")
Label(f1,text="Chickenmeal").grid(row=2,column=0)
Entry(f1,textvariable=cmeal).grid(row=2,column=1)
cmeal.set("")
Label(f1,text="Muttonmeal").grid(row=3,column=0)
Entry(f1,textvariable=mutton).grid(row=3,column=1)
mutton.set("")
Label(f1,text="Crab").grid(row=4,column=0)
Entry(f1,textvariable=crab).grid(row=4,column=1)
crab.set("")
Button(f1,text="Price").grid(row=5,column=0)
Button(f1,text="Total").grid(row=5,column=1)
Button(f1,text="Reset").grid(row=5,column=2)
Button(f1,text="Exit").grid(row=5,column=3)



f2=Frame(root,bg='#808000',width=600,height=600)
f2.pack(side=RIGHT)
d=datetime.datetime.now()
lbinfo=Label(TopF,text="Res management system",fg='black',bd=20)
lbinfo.grid(row=0,column=1)
lbltime=Label(TopF,text=d,fg='blue',bd=10)
lbltime.grid(row=1,column=1)
root.mainloop()
